name: amplitude_flutter_example
description: Demonstrates how to use the amplitude_flutter plugin.
publish_to: 'none'
version: 0.12.4

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  amplitude_flutter:
    path: ../
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
